spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect


cloud:
  aws:
    s3:
      bucket: tribillbucket
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIAWSDJ74GU7EMSBQVN
      secretKey: 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
